spring:
  security:
    oauth2:
      client:
        registration:
          hubspot:
            authorization-grant-type: authorization_code
            client-id: your-client-id
            client-secret: your-client-secret
            redirect-uri: https://yourapp.dev/oauth2/callback/hubspot
            client-authentication-method: client_secret_post
            scope: crm.objects.leads.read, settings.users.read
        provider:
          hubspot:
            authorization-uri: https://app-eu1.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token
            user-info-uri: https://api.hubapi.com/oauth/v1/access-tokens/{accessToken}
            user-name-attribute: hub_id
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-app-oauth2-webhooks
    username: stefano
    password:
logging:
  level:
    root: debug
